services:
  db:
    image: mariadb:12
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: viv
      MARIADB_USER: viv
      MARIADB_PASSWORD: w3brtc
      MARIADB_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/viv
      SPRING_DATASOURCE_USERNAME: viv
      SPRING_DATASOURCE_PASSWORD: w3brtc

    ports:
      - "8080:8080"

volumes:
  db-data: