CREATE TABLE IF NOT EXISTS USER (
  ID                   BIGINT AUTO_INCREMENT PRIMARY KEY,
  EMAIL                VARCHAR(255) NOT NULL,
  USERNAME             VARCHAR(255) NOT NULL,
  FIRST_NAME           VARCHAR(255) NOT NULL,
  LAST_NAME            VARCHAR(255),
  PASSWORD             VARCHAR(255) NOT NULL,
  PROFILE_PIC          VARCHAR(255),
  LAST_PASSWORD_UPDATE TIMESTAMP    NOT NULL,
  UNIQUE UNIQUE_EMAIL (EMAIL),
  UNIQUE UNIQUE_USERNAME (USERNAME)

);

CREATE TABLE IF NOT EXISTS ROSTER (
  ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
  OWNER   BIGINT       NOT NULL,
  CONTACT BIGINT       NOT NULL,
  STATUS  VARCHAR(255) NOT NULL,
  UNIQUE UNIQUE_INDEX (OWNER, CONTACT),
  FOREIGN KEY (OWNER) REFERENCES USER (ID)
    ON DELETE RESTRICT,
  FOREIGN KEY (CONTACT) REFERENCES USER (ID)
    ON DELETE RESTRICT
);
